# Generated by Django 4.2 on 2024-04-20 18:17

import cis.storage_backend
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# Inline copies kept so this frozen migration does not import the live module.
def _ticket_upload_path(instance, filename):
    return f"ticket/{instance.id}/{filename}"


def _ticket_note_upload_path(instance, filename):
    return f"ticket/{instance.support_ticket.id}/notes/{instance.id}/{filename}"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=_ticket_upload_path)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to_ticket_set', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('applies_to', models.CharField(choices=[('Students', 'Students'), ('High School Administrators', 'High School Administrators')], max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'applies_to')},
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal')], max_length=10)),
                ('media', models.FileField(blank=True, null=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=_ticket_note_upload_path)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('support_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='support_ticket.ticket')),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='support_ticket.tickettype'),
        ),
    ]
