# Generated by Django 5.2.15 on 2026-06-29 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='notify_emails',
            field=models.TextField(blank=True, help_text='Comma-separated extra email addresses to notify on submission.'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='notify_ticket_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='requires_attachment',
            field=models.BooleanField(default=False, help_text='Require at least one file when a ticket of this type is created.'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='applies_to',
            field=models.CharField(choices=[('Students', 'Students'), ('High School Administrators', 'High School Administrators'), ('Instructors', 'Instructors')], max_length=30),
        ),
    ]
