# Generated by Django 5.2.15 on 2026-06-29 16:38

from django.db import migrations


def forwards(apps, schema_editor):
    Ticket = apps.get_model('support_ticket', 'Ticket')
    TicketNote = apps.get_model('support_ticket', 'TicketNote')
    TicketAttachment = apps.get_model('support_ticket', 'TicketAttachment')

    for ticket in Ticket.objects.exclude(media='').exclude(media=None):
        TicketAttachment.objects.create(
            ticket_id=ticket.id, media=ticket.media,
            uploaded_by_id=ticket.submitted_by_id)

    for note in TicketNote.objects.exclude(media='').exclude(media=None):
        TicketAttachment.objects.create(
            note_id=note.id, media=note.media,
            uploaded_by_id=getattr(note, 'createdby_id', None))


def backwards(apps, schema_editor):
    # Irreversible data move; no-op reverse (attachments retained).
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('support_ticket', '0003_add_ticket_attachment'),
        ('cis', '__first__'),
    ]
    operations = [migrations.RunPython(forwards, backwards)]
