# Generated by Django 5.2.15 on 2026-06-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0004_migrate_media_to_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='media',
        ),
        migrations.RemoveField(
            model_name='ticketnote',
            name='media',
        ),
    ]
