# Generated by Django 5.2.15 on 2026-06-29 17:07

from django.db import migrations

OLD_KEY = 'support_ticket_settings'
NEW_KEY = 'support_ticket.settings.support_ticket_settings'


def forwards(apps, schema_editor):
    Setting = apps.get_model('cis', 'Setting')
    try:
        old = Setting.objects.get(key=OLD_KEY)
    except Setting.DoesNotExist:
        return
    new, created = Setting.objects.get_or_create(key=NEW_KEY, defaults={'value': {}})
    if created or not new.value:
        new.value = old.value or {}
    # Remap legacy email_subject -> note_subject (signals read note_subject).
    if old.value and 'email_subject' in old.value and 'note_subject' not in new.value:
        new.value['note_subject'] = old.value['email_subject']
    new.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0006_fix_ticket_dates_and_status'),
        ('cis', '__first__'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
