# Generated by Django 5.2.15 on 2026-06-29 18:39

import cis.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0007_migrate_legacy_settings_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='media',
            field=models.FileField(max_length=500, storage=cis.storage_backend.PrivateMediaStorage(), upload_to='support_ticket/attachments/%Y/%m/'),
        ),
    ]
