# Generated by Django 5.2.17 on 2026-09-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0008_alter_ticketattachment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='email_assignee',
            field=models.BooleanField(default=False, help_text='Email the assigned person whenever a ticket of this type is assigned to them.', verbose_name='Email assignee'),
        ),
    ]
