# Generated by Django 5.2.17 on 2026-09-25 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '__first__'),
        ('support_ticket', '0009_tickettype_email_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='cis.term'),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='emailed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='emailed_to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
